#!/usr/bin/env python3
"""Turn ``data/cores.json`` into ``stub/source/cores_table.h``.

Produces a static C table mapping ``core name -> Title ID``, embedded in the
forwarder stub so the Title ID and CIA path don't have to be duplicated in
each per-game RomFS (see ``cores_table.h`` itself for how the stub uses it).

Usage::

    python3 tools/generate_cores_table.py data/cores.json > stub/source/cores_table.h
"""

from __future__ import annotations

import json
import sys

HEADER_TEMPLATE = """/* AUTO-GENERATED by generate_cores_table.py from cores.json.
 * DO NOT EDIT BY HAND. To refresh after a RetroArch update:
 *
 *   python3 tools/parse_retroarch_cores.py <RetroArch>/pkg/ctr/Makefile.cores > data/cores.json
 *   python3 tools/generate_cores_table.py data/cores.json > stub/source/cores_table.h
 *
 * Total cores: {count}
 */
#ifndef _CORES_TABLE_H_
#define _CORES_TABLE_H_

#include <3ds/types.h>

typedef struct {{
    const char *libretro_name;
    u64 title_id;
    const char *cia_filename;
}} core_entry_t;

static const core_entry_t CORES_TABLE[] = {{
{entries}
}};

#define CORES_TABLE_COUNT (sizeof(CORES_TABLE) / sizeof(CORES_TABLE[0]))

#endif /* _CORES_TABLE_H_ */
"""

ENTRY_TEMPLATE = '    {{ "{name}", 0x{title_id}ULL, "{cia_filename}" }}, /* {title} */'


def generate(cores: dict) -> str:
    """Render the full C header for the given core map."""
    entries = []
    # Alphabetical order keeps header diffs readable.
    for name in sorted(cores.keys()):
        core = cores[name]
        title = core.get("title", name).replace('"', "'")
        entries.append(
            ENTRY_TEMPLATE.format(
                name=core["libretro_name"],
                title_id=core["title_id"],
                cia_filename=core["cia_filename"],
                title=title,
            )
        )

    return HEADER_TEMPLATE.format(count=len(cores), entries="\n".join(entries))


def main() -> None:
    """CLI entry point: read a cores.json path, print the header to stdout."""
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <cores.json>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        cores = json.load(handle)

    print(generate(cores))
    print(f"# Total entries generated: {len(cores)}", file=sys.stderr)


if __name__ == "__main__":
    main()
